### ISSUE TITLE
Missing qunit dependency after update to v4.1 -- ojet build crashes

### ISSUE THREAD

**Issue by janis-kra** [oracle/oraclejet-tooling#1]
I recently migrated from JET v3.0.0 to v4.1 and running `ojet build` crashes because it cannot find `qunit-reporter-junit`. Same goes for `qunit` after i manually installed the former. Seems that the `npmCopyConfig.js` file declares these files to be copeid to the libs folder, but they are not listed as a dependency in the package.json.

Manually installing both dependencies solved the issue, but I think they should at least be included in the package.json, or not mandatory at all because some people (like me) do not use QUnit for testing.

Thanks and keep up the good work! :)

Here's the error log upon running `ojet build`:

```
→ ojet build
 Oracle JET CLI
Warning: Missing platform. Default to web.
 Oracle JET Tooling
cleaning staging path.....
copy files to staging directory.....
copy finished...
copy library files to staging directory.....
{ Error: ENOENT: no such file or directory, stat 'node_modules/qunit-reporter-junit/qunit-reporter-junit.js'
    at Object.fs.statSync (fs.js:954:18)
    at Object.statSync (/Users/jk/dev/workspace/enpit/js/enpit.jet.travelcost/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (/Users/jk/dev/workspace/enpit/js/enpit.jet.travelcost/node_modules/@oracle/oraclejet-tooling/node_modules/fs-extra/lib/copy-sync/copy-sync.js:31:86)
    at Promise (/Users/jk/dev/workspace/enpit/js/enpit.jet.travelcost/node_modules/@oracle/oraclejet-tooling/lib/buildCommon.js:51:14)
    at _copyFileToStaging (/Users/jk/dev/workspace/enpit/js/enpit.jet.travelcost/node_modules/@oracle/oraclejet-tooling/lib/buildCommon.js:43:10)
    at _copyLibsToStaging (/Users/jk/dev/workspace/enpit/js/enpit.jet.travelcost/node_modules/@oracle/oraclejet-tooling/lib/buildCommon.js:249:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'node_modules/qunit-reporter-junit/qunit-reporter-junit.js' }
```

**Comment by peppertech** [comment]
This should be fixed in 4.2.  Please give it a try and reopen if there are still issues.
